{% set name = "pyxtensor" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/tdegeus/pyxtensor/archive/v{{ version }}.tar.gz
  sha256: "194f696f35ca201edb4f2eeee3784659511fe26e92cc30b5b3f6dcbf659e3e4b"

build:
  number: 1

requirements:
  build:
    - {{ compiler('cxx') }}
    - cmake
    - make  # [unix]
    - xtensor
  host:
    - python
    - pip
    - setuptools
  run:
    - python
    - setuptools
    - pkgconfig
    - pybind11
    - xtensor

test:
  imports:
    - pyxtensor
  commands:
    - test -d ${PREFIX}/include/pyxtensor  # [unix]
    - test -f ${PREFIX}/include/pyxtensor/pybind11_xarray.hpp  # [unix]
    - test -f ${PREFIX}/include/pyxtensor/pybind11_xtensor.hpp  # [unix]
    - test -f ${PREFIX}/include/pyxtensor/pybind11_xtensor_fixed.hpp  # [unix]
    - test -f ${PREFIX}/include/pyxtensor/pyxtensor.hpp  # [unix]
    - test -f ${PREFIX}/lib/cmake/pyxtensor/pyxtensorConfig.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\pyxtensor\pybind11_xarray.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\pyxtensor\pybind11_xtensor.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\pyxtensor\pybind11_xtensor_fixed.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\include\pyxtensor\pyxtensor.hpp (exit 0) else (exit 1)  # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\pyxtensorConfig.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/tdegeus/pyxtensor
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: pybind11 details for xtensor
  description: pybind11 details for xtensor
  doc_url: https://github.com/tdegeus/pyxtensor
  dev_url: https://github.com/tdegeus/pyxtensor

extra:
  recipe-maintainers:
    - tdegeus
